#!所有默认入口
#!https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties
#!!!格式非常重要 缩进也非常重要
#xjy:                 #自定义参数
#  userName: aaa      #一般形式
#  familyName:        #集合形式
#    - father
#server:
#  port: 8080             #端口号
#  servlet:
#    context-path: /boot  #context-path
#spring:
#  application:
#    name: server-manager
#  #1.测试 开发 正式环境部署
#  #  profiles:
#  #部署激活 谁在后面激活谁
#  #    active: dev,test
#  #web配置
#  #  web:
#  #资源配置
#  #    resources:
#  #2.静态资源配置 不配置默认 static 文件夹内
#  #      static-locations: classpath:/webapp
#  #数据库配置
#  datasource:
#    #德鲁伊连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #url:jdbc:mysql:///sm_db 本地数据库地址
#      url: jdbc:mysql:///sm_db
#      #账号
#      username: root
#      #密码
#      password: a123456
#      #驱动类
#      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  # 默认位置可以不写 classpath指resource下
#  mapper-locations: classpath:/mapper/*.xml
#  #配置
#  configuration:
#    #驼峰映射 数据库下划线改为驼峰命名
#    #    map-underscore-to-camel-case: true
#    #自动映射 一层 对所有的结果集进行自动映射，包括嵌套结果集。
#    #    auto-mapping-behavior: full
#    #log 日志配置Slf4jImpl
#    #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    #控制台输出sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #映射 type-aliases-package  mapper.xml / resultType / 模型类 首字母小写
#  type-aliases-package: com.atguigu.pojo
#  #全局配置
#  global-config:
#    #数据库配置
#    db-config:
#      #表名前缀 不用在每个实体类配置@TableName
#      table-prefix: news_
#      # 配置MyBatis-Plus的主键策略
#      id-type: auto
#      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-field: deleted
#      # 逻辑已删除值(默认为 1)
#      logic-delete-value: 1
#      # 逻辑未删除值(默认为 0)
#      logic-not-delete-value: 0
#mybatis:
#  config-location: classpath:/mybatis-config.xml
#  mapper-locations: classpath:/mapper/*/*.xml

server:
  port: 8500
spring:
  application:
    name: spzx-server-gateway
  data:
    redis:
      #1。需要虚拟机的地址
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #路由发现
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/api/order/cart/**
