######

#spring:
#  profiles:
#    active: dev
##    active: test

spring:
  cloud:
    nacos:
      config:
        server-addr: 172.80.0.19:8848
  config:
    import:
      - nacos:service-product-dev.yaml